const elementosNaoMetal = [1, 6, 7, 8, 15, 16, 34]
const elementosMetaisAlcalinos = [3, 11, 19, 37, 55, 87]
const elementoSemiMetais = [5, 14, 32, 33, 51, 52, 84]
const elementosOutrosMetais = [13, 31, 49, 50, 81, 82, 83, 113, 114, 115, 116]
const elementosGasesNobres = [2, 10, 18, 36, 54, 86, 118]
const elementosLantanideos = [57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71]
const elementosMetaisAlcalinoTerrosos = [4, 12, 20, 38, 56, 88]
const elementosHalogenios = [9, 17, 35, 53, 85, 117]
const elementosMetaisTransicao = [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 72, 73, 74, 75, 76, 77, 78, 79, 80, 104, 105, 106, 107, 108, 109, 110, 111, 112]
const elementosActinidios = [89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103]

const elementos = [
  { numeroAtomico: 1, simbolo: "H", nome: "Hidrogênio", massaAtomica: 1.01, configuracaoEletronica: "1s¹", grupoQuimico: "não metais" },
  { numeroAtomico: 2, simbolo: "He", nome: "Hélio", massaAtomica: 4.00, configuracaoEletronica: "1s²", grupoQuimico: "gases nobres" },
  { numeroAtomico: 3, simbolo: "Li", nome: "Lítio", massaAtomica: 6.94, configuracaoEletronica: "1s² 2s¹", grupoQuimico: "metais alcalinos" },
  { numeroAtomico: 4, simbolo: "Be", nome: "Berílio", massaAtomica: 9.01, configuracaoEletronica: "1s² 2s²", grupoQuimico: "metais alcalino-terrosos" },
  { numeroAtomico: 5, simbolo: "B", nome: "Boro", massaAtomica: 10.81, configuracaoEletronica: "1s² 2s² 2p¹", grupoQuimico: "semimetais" },
  { numeroAtomico: 6, simbolo: "C", nome: "Carbono", massaAtomica: 12.01, configuracaoEletronica: "1s² 2s² 2p²", grupoQuimico: "não metais" },
  { numeroAtomico: 7, simbolo: "N", nome: "Nitrogênio", massaAtomica: 14.01, configuracaoEletronica: "1s² 2s² 2p³", grupoQuimico: "não metais" },
  { numeroAtomico: 8, simbolo: "O", nome: "Oxigênio", massaAtomica: 16.00, configuracaoEletronica: "1s² 2s² 2p⁴", grupoQuimico: "não metais" },
  { numeroAtomico: 9, simbolo: "F", nome: "Flúor", massaAtomica: 19.00, configuracaoEletronica: "1s² 2s² 2p⁵", grupoQuimico: "halogênios" },
  { numeroAtomico: 10, simbolo: "Ne", nome: "Neônio", massaAtomica: 20.18, configuracaoEletronica: "1s² 2s² 2p⁶", grupoQuimico: "gases nobres" },
  { numeroAtomico: 11, simbolo: "Na", nome: "Sódio", massaAtomica: 22.99, configuracaoEletronica: "1s² 2s² 2p⁶ 3s¹", grupoQuimico: "metais alcalinos" },
  { numeroAtomico: 12, simbolo: "Mg", nome: "Magnésio", massaAtomica: 24.31, configuracaoEletronica: "1s² 2s² 2p⁶ 3s²", grupoQuimico: "metais alcalino-terrosos" },
  { numeroAtomico: 13, simbolo: "Al", nome: "Alumínio", massaAtomica: 26.98, configuracaoEletronica: "1s² 2s² 2p⁶ 3s² 3p¹", grupoQuimico: "metais representativos" },
  { numeroAtomico: 14, simbolo: "Si", nome: "Silício", massaAtomica: 28.09, configuracaoEletronica: "1s² 2s² 2p⁶ 3s² 3p²", grupoQuimico: "semimetais" },
  { numeroAtomico: 15, simbolo: "P", nome: "Fósforo", massaAtomica: 30.97, configuracaoEletronica: "1s² 2s² 2p⁶ 3s² 3p³", grupoQuimico: "não metais" },
  { numeroAtomico: 16, simbolo: "S", nome: "Enxofre", massaAtomica: 32.07, configuracaoEletronica: "1s² 2s² 2p⁶ 3s² 3p⁴", grupoQuimico: "não metais" },
  { numeroAtomico: 17, simbolo: "Cl", nome: "Cloro", massaAtomica: 35.45, configuracaoEletronica: "1s² 2s² 2p⁶ 3s² 3p⁵", grupoQuimico: "halogênios" },
  { numeroAtomico: 18, simbolo: "Ar", nome: "Argônio", massaAtomica: 39.95, configuracaoEletronica: "1s² 2s² 2p⁶ 3s² 3p⁶", grupoQuimico: "gases nobres" },
  { numeroAtomico: 19, simbolo: "K", nome: "Potássio", massaAtomica: 39.10, configuracaoEletronica: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹", grupoQuimico: "metais alcalinos" },
  { numeroAtomico: 20, simbolo: "Ca", nome: "Cálcio", massaAtomica: 40.08, configuracaoEletronica: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s²", grupoQuimico: "metais alcalino-terrosos" },
  { numeroAtomico: 21, simbolo: "Sc", nome: "Escândio", massaAtomica: 44.96, configuracaoEletronica: "[Ar] 3d¹ 4s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 22, simbolo: "Ti", nome: "Titânio", massaAtomica: 47.87, configuracaoEletronica: "[Ar] 3d² 4s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 23, simbolo: "V", nome: "Vanádio", massaAtomica: 50.94, configuracaoEletronica: "[Ar] 3d³ 4s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 24, simbolo: "Cr", nome: "Cromo", massaAtomica: 51.99, configuracaoEletronica: "[Ar] 3d⁵ 4s¹", grupoQuimico: "metais de transição" },
  { numeroAtomico: 25, simbolo: "Mn", nome: "Manganês", massaAtomica: 54.94, configuracaoEletronica: "[Ar] 3d⁵ 4s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 26, simbolo: "Fe", nome: "Ferro", massaAtomica: 55.85, configuracaoEletronica: "[Ar] 3d⁶ 4s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 27, simbolo: "Co", nome: "Cobalto", massaAtomica: 58.93, configuracaoEletronica: "[Ar] 3d⁷ 4s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 28, simbolo: "Ni", nome: "Níquel", massaAtomica: 58.69, configuracaoEletronica: "[Ar] 3d⁸ 4s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 29, simbolo: "Cu", nome: "Cobre", massaAtomica: 63.55, configuracaoEletronica: "[Ar] 3d¹⁰ 4s¹", grupoQuimico: "metais de transição" },
  { numeroAtomico: 30, simbolo: "Zn", nome: "Zinco", massaAtomica: 65.38, configuracaoEletronica: "[Ar] 3d¹⁰ 4s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 31, simbolo: "Ga", nome: "Gálio", massaAtomica: 69.72, configuracaoEletronica: "[Ar] 3d¹⁰ 4s² 4p¹", grupoQuimico: "metais representativos" },
  { numeroAtomico: 32, simbolo: "Ge", nome: "Germânio", massaAtomica: 72.63, configuracaoEletronica: "[Ar] 3d¹⁰ 4s² 4p²", grupoQuimico: "semimetais" },
  { numeroAtomico: 33, simbolo: "As", nome: "Arsênio", massaAtomica: 74.92, configuracaoEletronica: "[Ar] 3d¹⁰ 4s² 4p³", grupoQuimico: "semimetais" },
  { numeroAtomico: 34, simbolo: "Se", nome: "Selênio", massaAtomica: 78.96, configuracaoEletronica: "[Ar] 3d¹⁰ 4s² 4p⁴", grupoQuimico: "não metais" },
  { numeroAtomico: 35, simbolo: "Br", nome: "Bromo", massaAtomica: 79.90, configuracaoEletronica: "[Ar] 3d¹⁰ 4s² 4p⁵", grupoQuimico: "halogênios" },
  { numeroAtomico: 36, simbolo: "Kr", nome: "Criptônio", massaAtomica: 83.80, configuracaoEletronica: "[Ar] 3d¹⁰ 4s² 4p⁶", grupoQuimico: "gases nobres" },
  { numeroAtomico: 37, simbolo: "Rb", nome: "Rubídio", massaAtomica: 85.47, configuracaoEletronica: "[Kr] 5s¹", grupoQuimico: "metais alcalinos" },
  { numeroAtomico: 38, simbolo: "Sr", nome: "Estrôncio", massaAtomica: 87.62, configuracaoEletronica: "[Kr] 5s²", grupoQuimico: "metais alcalino-terrosos" },
  { numeroAtomico: 39, simbolo: "Y", nome: "Ítrio", massaAtomica: 88.91, configuracaoEletronica: "[Kr] 4d¹ 5s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 40, simbolo: "Zr", nome: "Zircônio", massaAtomica: 91.22, configuracaoEletronica: "[Kr] 4d² 5s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 41, simbolo: "Nb", nome: "Nióbio", massaAtomica: 92.91, configuracaoEletronica: "[Kr] 4d⁴ 5s¹", grupoQuimico: "metais de transição" },
  { numeroAtomico: 42, simbolo: "Mo", nome: "Molibdênio", massaAtomica: 95.95, configuracaoEletronica: "[Kr] 4d⁵ 5s¹", grupoQuimico: "metais de transição" },
  { numeroAtomico: 43, simbolo: "Tc", nome: "Tecnécio", massaAtomica: 98.00, configuracaoEletronica: "[Kr] 4d⁵ 5s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 44, simbolo: "Ru", nome: "Rutênio", massaAtomica: 101.07, configuracaoEletronica: "[Kr] 4d⁷ 5s¹", grupoQuimico: "metais de transição" },
  { numeroAtomico: 45, simbolo: "Rh", nome: "Ródio", massaAtomica: 102.91, configuracaoEletronica: "[Kr] 4d⁸ 5s¹", grupoQuimico: "metais de transição" },
  { numeroAtomico: 46, simbolo: "Pd", nome: "Paládio", massaAtomica: 106.42, configuracaoEletronica: "[Kr] 4d¹⁰", grupoQuimico: "metais de transição" },
  { numeroAtomico: 47, simbolo: "Ag", nome: "Prata", massaAtomica: 107.87, configuracaoEletronica: "[Kr] 4d¹⁰ 5s¹", grupoQuimico: "metais de transição" },
  { numeroAtomico: 48, simbolo: "Cd", nome: "Cádmio", massaAtomica: 112.41, configuracaoEletronica: "[Kr] 4d¹⁰ 5s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 49, simbolo: "In", nome: "Índio", massaAtomica: 114.82, configuracaoEletronica: "[Kr] 4d¹⁰ 5s² 5p¹", grupoQuimico: "metais representativos" },
  { numeroAtomico: 50, simbolo: "Sn", nome: "Estanho", massaAtomica: 118.71, configuracaoEletronica: "[Kr] 4d¹⁰ 5s² 5p²", grupoQuimico: "metais representativos" },
  { numeroAtomico: 51, simbolo: "Sb", nome: "Antimônio", massaAtomica: 121.76, configuracaoEletronica: "[Kr] 4d¹⁰ 5s² 5p³", grupoQuimico: "semimetais" },
  { numeroAtomico: 52, simbolo: "Te", nome: "Telúrio", massaAtomica: 127.60, configuracaoEletronica: "[Kr] 4d¹⁰ 5s² 5p⁴", grupoQuimico: "semimetais" },
  { numeroAtomico: 53, simbolo: "I", nome: "Iodo", massaAtomica: 126.90, configuracaoEletronica: "[Kr] 4d¹⁰ 5s² 5p⁵", grupoQuimico: "halogênios" },
  { numeroAtomico: 54, simbolo: "Xe", nome: "Xenônio", massaAtomica: 131.29, configuracaoEletronica: "[Kr] 4d¹⁰ 5s² 5p⁶", grupoQuimico: "gases nobres" },
  { numeroAtomico: 55, simbolo: "Cs", nome: "Césio", massaAtomica: 132.91, configuracaoEletronica: "[Xe] 6s¹", grupoQuimico: "metais alcalinos" },
  { numeroAtomico: 56, simbolo: "Ba", nome: "Bário", massaAtomica: 137.33, configuracaoEletronica: "[Xe] 6s²", grupoQuimico: "metais alcalino-terrosos" },
  { numeroAtomico: 57, simbolo: "La", nome: "Lantânio", massaAtomica: 138.91, configuracaoEletronica: "[Xe] 5d¹ 6s²", grupoQuimico: "lantanídeos" },
  { numeroAtomico: 58, simbolo: "Ce", nome: "Cério", massaAtomica: 140.12, configuracaoEletronica: "[Xe] 4f¹ 5d¹ 6s²", grupoQuimico: "lantanídeos" },
  { numeroAtomico: 59, simbolo: "Pr", nome: "Praseodímio", massaAtomica: 140.91, configuracaoEletronica: "[Xe] 4f³ 6s²", grupoQuimico: "lantanídeos" },
  { numeroAtomico: 60, simbolo: "Nd", nome: "Neodímio", massaAtomica: 144.24, configuracaoEletronica: "[Xe] 4f⁴ 6s²", grupoQuimico: "lantanídeos" },
  { numeroAtomico: 61, simbolo: "Pm", nome: "Promécio", massaAtomica: 145.00, configuracaoEletronica: "[Xe] 4f⁵ 6s²", grupoQuimico: "lantanídeos" },
  { numeroAtomico: 62, simbolo: "Sm", nome: "Samário", massaAtomica: 150.36, configuracaoEletronica: "[Xe] 4f⁶ 6s²", grupoQuimico: "lantanídeos" },
  { numeroAtomico: 63, simbolo: "Eu", nome: "Európio", massaAtomica: 151.96, configuracaoEletronica: "[Xe] 4f⁷ 6s²", grupoQuimico: "lantanídeos" },
  { numeroAtomico: 64, simbolo: "Gd", nome: "Gadolínio", massaAtomica: 157.25, configuracaoEletronica: "[Xe] 4f⁷ 5d¹ 6s²", grupoQuimico: "lantanídeos" },
  { numeroAtomico: 65, simbolo: "Tb", nome: "Térbio", massaAtomica: 158.93, configuracaoEletronica: "[Xe] 4f⁹ 6s²", grupoQuimico: "lantanídeos" },
  { numeroAtomico: 66, simbolo: "Dy", nome: "Disprósio", massaAtomica: 162.50, configuracaoEletronica: "[Xe] 4f¹⁰ 6s²", grupoQuimico: "lantanídeos" },
  { numeroAtomico: 67, simbolo: "Ho", nome: "Hólmio", massaAtomica: 164.93, configuracaoEletronica: "[Xe] 4f¹¹ 6s²", grupoQuimico: "lantanídeos" },
  { numeroAtomico: 68, simbolo: "Er", nome: "Érbio", massaAtomica: 167.26, configuracaoEletronica: "[Xe] 4f¹² 6s²", grupoQuimico: "lantanídeos" },
  { numeroAtomico: 69, simbolo: "Tm", nome: "Túlio", massaAtomica: 168.93, configuracaoEletronica: "[Xe] 4f¹³ 6s²", grupoQuimico: "lantanídeos" },
  { numeroAtomico: 70, simbolo: "Yb", nome: "Itérbio", massaAtomica: 173.04, configuracaoEletronica: "[Xe] 4f¹⁴ 6s²", grupoQuimico: "lantanídeos" },
  { numeroAtomico: 71, simbolo: "Lu", nome: "Lutécio", massaAtomica: 174.97, configuracaoEletronica: "[Xe] 4f¹⁴ 5d¹ 6s²", grupoQuimico: "lantanídeos" },
  { numeroAtomico: 72, simbolo: "Hf", nome: "Háfnio", massaAtomica: 178.49, configuracaoEletronica: "[Xe] 4f¹⁴ 5d² 6s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 73, simbolo: "Ta", nome: "Tântalo", massaAtomica: 180.95, configuracaoEletronica: "[Xe] 4f¹⁴ 5d³ 6s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 74, simbolo: "W", nome: "Tungstênio", massaAtomica: 183.84, configuracaoEletronica: "[Xe] 4f¹⁴ 5d⁴ 6s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 75, simbolo: "Re", nome: "Rênio", massaAtomica: 186.21, configuracaoEletronica: "[Xe] 4f¹⁴ 5d⁵ 6s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 76, simbolo: "Os", nome: "Ósmio", massaAtomica: 190.23, configuracaoEletronica: "[Xe] 4f¹⁴ 5d⁶ 6s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 77, simbolo: "Ir", nome: "Irídio", massaAtomica: 192.22, configuracaoEletronica: "[Xe] 4f¹⁴ 5d⁷ 6s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 78, simbolo: "Pt", nome: "Platina", massaAtomica: 195.08, configuracaoEletronica: "[Xe] 4f¹⁴ 5d⁹ 6s¹", grupoQuimico: "metais de transição" },
  { numeroAtomico: 79, simbolo: "Au", nome: "Ouro", massaAtomica: 196.97, configuracaoEletronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹", grupoQuimico: "metais de transição" },
  { numeroAtomico: 80, simbolo: "Hg", nome: "Mercúrio", massaAtomica: 200.59, configuracaoEletronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 81, simbolo: "Tl", nome: "Tálio", massaAtomica: 204.38, configuracaoEletronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹", grupoQuimico: "metais pobres" },
  { numeroAtomico: 82, simbolo: "Pb", nome: "Chumbo", massaAtomica: 207.2, configuracaoEletronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²", grupoQuimico: "metais pobres" },
  { numeroAtomico: 83, simbolo: "Bi", nome: "Bismuto", massaAtomica: 208.98, configuracaoEletronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³", grupoQuimico: "metais pobres" },
  { numeroAtomico: 84, simbolo: "Po", nome: "Polônio", massaAtomica: 209.00, configuracaoEletronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴", grupoQuimico: "semimetais" },
  { numeroAtomico: 85, simbolo: "At", nome: "Ástato", massaAtomica: 210.00, configuracaoEletronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵", grupoQuimico: "halogênios" },
  { numeroAtomico: 86, simbolo: "Rn", nome: "Radônio", massaAtomica: 222.00, configuracaoEletronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶", grupoQuimico: "gases nobres" },
  { numeroAtomico: 87, simbolo: "Fr", nome: "Frâncio", massaAtomica: 223.00, configuracaoEletronica: "[Rn] 7s¹", grupoQuimico: "metais alcalinos" },
  { numeroAtomico: 88, simbolo: "Ra", nome: "Rádio", massaAtomica: 226.00, configuracaoEletronica: "[Rn] 7s²", grupoQuimico: "metais alcalino-terrosos" },
  { numeroAtomico: 89, simbolo: "Ac", nome: "Actínio", massaAtomica: 227.00, configuracaoEletronica: "[Rn] 6d¹ 7s²", grupoQuimico: "actinídeos" },
  { numeroAtomico: 90, simbolo: "Th", nome: "Tório", massaAtomica: 232.04, configuracaoEletronica: "[Rn] 6d² 7s²", grupoQuimico: "actinídeos" },
  { numeroAtomico: 91, simbolo: "Pa", nome: "Protactínio", massaAtomica: 231.04, configuracaoEletronica: "[Rn] 5f² 6d¹ 7s²", grupoQuimico: "actinídeos" },
  { numeroAtomico: 92, simbolo: "U", nome: "Urânio", massaAtomica: 238.03, configuracaoEletronica: "[Rn] 5f³ 6d¹ 7s²", grupoQuimico: "actinídeos" },
  { numeroAtomico: 93, simbolo: "Np", nome: "Netúnio", massaAtomica: 237.00, configuracaoEletronica: "[Rn] 5f⁴ 6d¹ 7s²", grupoQuimico: "actinídeos" },
  { numeroAtomico: 94, simbolo: "Pu", nome: "Plutônio", massaAtomica: 244.00, configuracaoEletronica: "[Rn] 5f⁶ 7s²", grupoQuimico: "actinídeos" },
  { numeroAtomico: 95, simbolo: "Am", nome: "Amerício", massaAtomica: 243.00, configuracaoEletronica: "[Rn] 5f⁷ 7s²", grupoQuimico: "actinídeos" },
  { numeroAtomico: 96, simbolo: "Cm", nome: "Cúrio", massaAtomica: 247.00, configuracaoEletronica: "[Rn] 5f⁷ 6d¹ 7s²", grupoQuimico: "actinídeos" },
  { numeroAtomico: 97, simbolo: "Bk", nome: "Berquélio", massaAtomica: 247.00, configuracaoEletronica: "[Rn] 5f⁹ 7s²", grupoQuimico: "actinídeos" },
  { numeroAtomico: 98, simbolo: "Cf", nome: "Califórnio", massaAtomica: 251.00, configuracaoEletronica: "[Rn] 5f¹⁰ 7s²", grupoQuimico: "actinídeos" },
  { numeroAtomico: 99, simbolo: "Es", nome: "Einstênio", massaAtomica: 252.00, configuracaoEletronica: "[Rn] 5f¹¹ 7s²", grupoQuimico: "actinídeos" },
  { numeroAtomico: 100, simbolo: "Fm", nome: "Férmio", massaAtomica: 257.00, configuracaoEletronica: "[Rn] 5f¹² 7s²", grupoQuimico: "actinídeos" },
  { numeroAtomico: 101, simbolo: "Md", nome: "Mendelévio", massaAtomica: 258.00, configuracaoEletronica: "[Rn] 5f¹³ 7s²", grupoQuimico: "actinídeos" },
  { numeroAtomico: 102, simbolo: "No", nome: "Nobélio", massaAtomica: 259.00, configuracaoEletronica: "[Rn] 5f¹⁴ 7s²", grupoQuimico: "actinídeos" },
  { numeroAtomico: 103, simbolo: "Lr", nome: "Laurêncio", massaAtomica: 262.00, configuracaoEletronica: "[Rn] 5f¹⁴ 7s² 7p¹", grupoQuimico: "actinídeos" },
  { numeroAtomico: 104, simbolo: "Rf", nome: "Rutherfórdio", massaAtomica: 267.00, configuracaoEletronica: "[Rn] 5f¹⁴ 6d² 7s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 105, simbolo: "Db", nome: "Dúbnio", massaAtomica: 270.00, configuracaoEletronica: "[Rn] 5f¹⁴ 6d³ 7s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 106, simbolo: "Sg", nome: "Seabórgio", massaAtomica: 271.00, configuracaoEletronica: "[Rn] 5f¹⁴ 6d⁴ 7s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 107, simbolo: "Bh", nome: "Bóhrio", massaAtomica: 270.00, configuracaoEletronica: "[Rn] 5f¹⁴ 6d⁵ 7s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 108, simbolo: "Hs", nome: "Hássio", massaAtomica: 277.00, configuracaoEletronica: "[Rn] 5f¹⁴ 6d⁶ 7s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 109, simbolo: "Mt", nome: "Meitnério", massaAtomica: 278.00, configuracaoEletronica: "[Rn] 5f¹⁴ 6d⁷ 7s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 110, simbolo: "Ds", nome: "Darmstádio", massaAtomica: 281.00, configuracaoEletronica: "[Rn] 5f¹⁴ 6d⁸ 7s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 111, simbolo: "Rg", nome: "Roentgênio", massaAtomica: 282.00, configuracaoEletronica: "[Rn] 5f¹⁴ 6d⁹ 7s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 112, simbolo: "Cn", nome: "Copernício", massaAtomica: 285.00, configuracaoEletronica: "[Rn] 5f¹⁴ 6d¹⁰ 7s²", grupoQuimico: "metais de transição" },
  { numeroAtomico: 113, simbolo: "Nh", nome: "Nihônio", massaAtomica: 286.00, configuracaoEletronica: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹", grupoQuimico: "metais pobres" },
  { numeroAtomico: 114, simbolo: "Fl", nome: "Fleróvio", massaAtomica: 289.00, configuracaoEletronica: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²", grupoQuimico: "metais pobres" },
  { numeroAtomico: 115, simbolo: "Mc", nome: "Moscóvio", massaAtomica: 290.00, configuracaoEletronica: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³", grupoQuimico: "metais pobres" },
  { numeroAtomico: 116, simbolo: "Lv", nome: "Livermório", massaAtomica: 293.00, configuracaoEletronica: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴", grupoQuimico: "metais pobres" },
  { numeroAtomico: 117, simbolo: "Ts", nome: "Tenessino", massaAtomica: 294.00, configuracaoEletronica: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵", grupoQuimico: "halogênios" },
  { numeroAtomico: 118, simbolo: "Og", nome: "Oganessônio", massaAtomica: 294.00, configuracaoEletronica: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶", grupoQuimico: "gases nobres" }
];


export {
  elementosNaoMetal,
  elementosMetaisAlcalinos,
  elementoSemiMetais,
  elementosOutrosMetais,
  elementosGasesNobres,
  elementosLantanideos,
  elementosMetaisAlcalinoTerrosos,
  elementosHalogenios,
  elementosMetaisTransicao,
  elementosActinidios,
  elementos
}
